## numpy array vs python list 

In [2]:
# python 

a = [1,2,3,4,5]

print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [22]:
b = [1,2,3,4,5]

print(a + b)
print(3 * a)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### notice: mathmatical operation does not work with python list

let us try numpy instead

In [3]:
import numpy as np 

In [15]:
n = np.array([1,2,3,4,5])
print(f'python list : {a}')
print(f'numpy array : {n}')
print(type(n))

python list : [1, 2, 3, 4, 5]
numpy array : [1 2 3 4 5]
<class 'numpy.ndarray'>


## 1.Basic numpy operation 

### 1.1 slicing and modifying 

In [16]:
print(n[1])
print(n[2:])
print(n[:-2])
print(n[0], n[1])

2
[3 4 5]
[1 2 3]
1 2


In [62]:
n[0] = 10
print(n)

[10  2  3  4  5]


#### same as python list 

### 1.2 basic math with numpy 

In [20]:
n = np.array([1,2,3,4,5])
p = np.array([1,2,3,4,5])

print(n + p)
print(n - p)

[ 2  4  6  8 10]
[0 0 0 0 0]


### using python list:

In [68]:
n = np.array([1,2,3,4,5])
p = np.array([1,2,3,4,5])
total = []

for i in range(len(n)):
    total.append(n[i] + p[i])

print(total)

[2, 4, 6, 8, 10]


### back to numpy 

In [19]:
print(2 + n)
print(2 - n)
print(2 * n)
print(2 / n)
print( n **2 )

[3 4 5 6 7]
[ 1  0 -1 -2 -3]
[ 2  4  6  8 10]
[2.         1.         0.66666667 0.5        0.4       ]
[ 1  4  9 16 25]


## 1.3 array attributes and dimention 

#### 1d array  (vectors)

In [83]:
# 1d array 

a = np.array([1,2,3,4])
print(type(a))
print(a) 
print(a.ndim) # returns the number of dimensions 
print(a.shape) # returns the number of dimensions, size of the array along that dimension)
print(a.size) # returns total number of elements in the array 
print(a.dtype) # returns the datatype of the element in the array 
print(a.itemsize) # returns the byte size of each element in the array (8 for int64, 4 for int32)

<class 'numpy.ndarray'>
[1 2 3 4]
1
(4,)
4
int64
8


In [71]:
a = np.array([1,'hi',3,4])
print(type(a)) 
print(a.ndim) 
print(a.shape) 
print(a.size) 
print(a.dtype) 
print(a.itemsize) 
print(type(a[1]))

<class 'numpy.ndarray'>
1
(4,)
4
<U21
84
<class 'numpy.str_'>


### numpy array allow specifying data types 

In [44]:
b = np.array([1,'5',3,4])
print(b.dtype)

b = np.array([1,'5',3,4], dtype= np.int32)
print(b.dtype)

<U21
int32


#### 2d array (matrix)

In [82]:
#2d

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


### 3d array (tensor)

In [75]:
# 3d 

a = np.array([[1,2,3],[4,5,6]],[7,8,9])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

TypeError: Field elements must be 2- or 3-tuples, got '7'

### note: 

1d array: is a simple array (n,)\
2d array: is an array of arrays (n,n)\
3d array: is an array 2d array (n,n,n)

In [81]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(f'number of dimensions: {a.ndim}')
print(f'number of layers, rows, columns: {a.shape}')
print(f'total number of elements in the array : {a.size}')
print(a.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
number of dimensions: 3
number of layers, rows, columns: (2, 2, 3)
total number of elements in the array : 12
int64


### Reshaping 

In [109]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(f'number of layers, rows, columns: {a.shape}')


a = a.reshape(3,2)
print(a)
print(f'number of layers, rows, columns: {a.shape}')

[[1 2 3]
 [4 5 6]]
number of layers, rows, columns: (2, 3)
[[1 2]
 [3 4]
 [5 6]]
number of layers, rows, columns: (3, 2)


## 1.4 creating numpy array 

In [87]:
a = np.arange(5) # starts from zero to n
a

array([0, 1, 2, 3, 4])

In [91]:
a = np.arange(10,110, 10) #starts from 10 to 100 with step of 10
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [93]:
a = np.linspace(0, 1, 5) # start from 0 to 1, with 5 evenly spaced between 0 and 1
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [95]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [100]:
a = np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### task: create a 2x2 matrix of 10

In [112]:
a = np.ones((2,2)) * 10
a

array([[10., 10.],
       [10., 10.]])

In [102]:
a = np.full((2,3), 5)
a

array([[5, 5, 5],
       [5, 5, 5]])

#### another solution to the task :

In [113]:
a = np.full((2,2), 10)
a

array([[10, 10],
       [10, 10]])

In [104]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 1.5 Array Manipulation

### stack 

In [116]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.stack([a,b])
print(c)

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.stack([a,b], axis= 1)
print(c)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### split 

In [118]:
a = np.array([1,2,3,4,5,6])

b = np.split(a,3)
b

[array([1, 2]), array([3, 4]), array([5, 6])]

## task: try to find out the code for this output


[[5 5 5 5 5]
 [5 1 1 1 5]
 [5 1 0 1 5]
 [5 1 1 1 5]
 [5 5 5 5 5]]


## 2. Linear algebra with numpy

## 2.1  multiplication 

### vector multiplication

In [167]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# element-wise -> vector

print(a * b) 

# dot product -> scaler

print(np.dot(a,b))

# cross product -> vector 

print(np.cross(a,b))

[ 4 10 18]
32
[-3  6 -3]


### matrix multiplication

In [163]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6], [7,8]])

# element-wise -> matrix

print(a * b) 

# dot product -> matrix

print(np.dot(a,b))

# cross product -> vector 

print(np.cross(a,b))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[-4 -4]


### 2.2 Matrix operations 

### transpose

In [164]:
a = np.array([[1,2],[3,4]])
print(a)
t = np.transpose(a)
print(t)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### inverse

In [165]:
a = np.array([[1,2],[3,4]])
i = np.linalg.inv(a)
print(i)

[[-2.   1. ]
 [ 1.5 -0.5]]


### determinant

In [166]:
a = np.array([[1,2],[3,4]])
d = np.linalg.det(a)
print(d)

-2.0000000000000004


### flatten 

## 3. aggregate functions 

In [168]:
a = np.array([100, 1, 2, 3, 4, 5])
a

array([100,   1,   2,   3,   4,   5])

In [169]:
a.min()

1

In [170]:
a.max()

100

In [171]:
a.mean()

19.166666666666668

In [172]:
a.std()

36.17281053805775

In [174]:
a.sort()
a

array([  1,   2,   3,   4,   5, 100])

In [176]:
a.argmax()

5

In [177]:
a.argmin()

0

In [179]:
b = a.argsort()
b

array([0, 1, 2, 3, 4, 5])

## 4. random functions

In [193]:
a = np.random.rand(5) # generates random numbers from zero to one from a uniform distribution
print(a)

b = np.random.randn(5) #generates random numbers from standard normal dist (mean = 0, standard deviation = 1)
print(b)

c = np.random.randint(5) #generates random number from range(n)
print(c)

d = np.random.choice([1,2,3,4,5], size= 2) 
print(d)
e = np.array([1,2,3,4,5])
np.random.shuffle(e)
print(e)

[0.4920134  0.92770599 0.72561643 0.54696887 0.18655702]
[-0.47579162 -1.51622811  0.03692424  0.10560946 -0.59352783]
0
[4 5]
[5 3 2 4 1]


In [27]:
A = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

print(A[0, :, 0:2])

[[12 11]
 [ 9  8]]
